name: attiny85 AVR8JS Test

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'examples/**/*.ino'
      - 'examples/**/*.cpp'
      - 'examples/**/*.h'
      - 'platformio.ini'
      - 'CMakeLists.txt'
      - 'library.json'
      - '.github/workflows/avr8js_attiny85_test.yml'
      - '.github/workflows/avr8js_docker_template.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**/*.cpp'
      - 'src/**/*.h'
      - 'examples/**/*.ino'
      - 'examples/**/*.cpp'
      - 'examples/**/*.h'
      - 'platformio.ini'
      - 'CMakeLists.txt'
      - 'library.json'
      - '.github/workflows/avr8js_attiny85_test.yml'
      - '.github/workflows/avr8js_docker_template.yml'

jobs:
  attiny85_avr8js_test:
    uses: ./.github/workflows/avr8js_docker_template.yml
    with:
      platform: attiny85
      platform_display: ATtiny85
      sketch: Test
